version: "3"

services:
  php81:
    container_name: php81
    image: lamp-php:8.1-nodejs-apache
    restart: always
    ports:
      - 8081:80
      - 80:80
      - 443:443
    volumes:
      - .:/var/www/html:Z
      # # NOTE: メールを使用する場合はmsmtprcを作成しマウントさせる。
      # - ./msmtprc:/etc/msmtprc:ro
  php80:
    container_name: php80
    image: lamp-php:8.0-nodejs-apache
    restart: always
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html:Z
      # # NOTE: メールを使用する場合はmsmtprcを作成しマウントさせる。
      # - ./msmtprc:/etc/msmtprc:ro
  php74:
    container_name: php74
    image: lamp-php:7.4-nodejs-apache
    restart: always
    ports:
      - 8074:80
    volumes:
      - .:/var/www/html:Z
      # # NOTE: メールを使用する場合はmsmtprcを作成しマウントさせる。
      # - ./msmtprc:/etc/msmtprc:ro
  php73:
    container_name: php73
    image: lamp-php:7.3-nodejs-apache
    restart: always
    ports:
      - 8073:80
    volumes:
      - .:/var/www/html:Z
      # # NOTE: メールを使用する場合はmsmtprcを作成しマウントさせる。
      # - ./msmtprc:/etc/msmtprc:ro
  mysql55:
    container_name: mysql55
    image: lamp-mysql:5.5
    restart: always
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=database_name
      - MYSQL_USER=appuser
      - MYSQL_PASSWORD=devpass
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - mysql55
    ports:
      - "8306:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql55
      - PMA_USER=root
      - PMA_PASSWORD=root
      - MEMORY_LIMIT=200M
      - UPLOAD_LIMIT=200M
      - MAX_EXECUTION_TIME=0
volumes:
  data:
    external: true
    name: example-db
