version: "3"

services:
  apache-php74:
    container_name: example_web74
    image: lamp_apache-php74
    restart: always
    ports:
      - 8074:80
      - 80:80
      - 443:443
    volumes:
      - .:/var/www/html:Z
      # # MEMO: メールを使用する場合はmsmtprcを作成しマウントさせる。
      # - ./msmtprc:/etc/msmtprc:ro
