version: "3.9"

services:
  php81:
    image: lamp-php:8.1-nodejs-apache
    build:
      context: ./
      dockerfile: ./containers/apache-2.4/php-8.1-nodejs/Dockerfile
      args:
        - UID=${UID}
  # apache-php80:
  #   build:
  #     context: ./containers
  #     dockerfile: ./apache24/php80/Dockerfile
  #     args:
  #       - UID=${UID}
  # apache-php74:
  #   build:
  #     context: ./containers
  #     dockerfile: ./apache24/php74/Dockerfile
  #     args:
  #       - UID=${UID}
  # apache-php73:
  #   build:
  #     context: ./containers
  #     dockerfile: ./apache24/php73/Dockerfile
  #     args:
  #       - UID=${UID}
  # mariadb55:
  #   build: ./containers/mariadb55
