version: "3.9"

services:
  php81:
    image: lamp-php:8.1-nodejs-apache
    build:
      context: ./
      dockerfile: ./containers/apache-2.4/php-8.1-nodejs/Dockerfile
      args:
        - UID=${UID}
  php80:
    image: lamp-php:8.0-nodejs-apache
    build:
      context: ./
      dockerfile: ./containers/apache-2.4/php-8.0-nodejs/Dockerfile
      args:
        - UID=${UID}
  php74:
    image: lamp-php:7.4-nodejs-apache
    build:
      context: ./
      dockerfile: ./containers/apache-2.4/php-7.4-nodejs/Dockerfile
      args:
        - UID=${UID}
  php73:
    image: lamp-php:7.3-nodejs-apache
    build:
      context: ./
      dockerfile: ./containers/apache-2.4/php-7.3-nodejs/Dockerfile
      args:
        - UID=${UID}
  mysql55:
    image: lamp-mysql:5.5
    build: ./containers/mysql-5.5
  mariadb10:
    image: lamp-mariadb:10.7
    build: ./containers/mariadb-10.7
