version: '3.9'

services:
  api:
    hostname: api
    image: lamp-apache:2.4-bullseye
    ports:
      - 80:80
      - 443:443
    depends_on:
      - php81
      - php80
      - php74
    volumes:
      - selfcert:/usr/local/apache2/certs:ro,cached
      # NOTE: /public is DocumentRoot.
      # - ./.devcontainer/apache-2.4/vhosts:/usr/local/apache2/conf/vhosts:ro
      - .:/var/www/html:cached
  php81:
    hostname: php81
    image: lamp-php-fpm:8.1-nodejs-bullseye
    volumes:
      - .:/var/www/html:cached
  php80:
    hostname: php80
    image: lamp-php-fpm:8.0-nodejs-bullseye
    volumes:
      - .:/var/www/html:cached
  php74:
    hostname: php74
    image: lamp-php-fpm:7.4-nodejs-bullseye
    volumes:
      - .:/var/www/html:cached
  db:
    image: lamp-mariadb:10.8
    restart: always
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=${database_default_database}
      - MYSQL_USER=${database_default_username}
      - MYSQL_PASSWORD=${database_default_password}
  phpmyadmin:
    hostname: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${database_default_hostname}
      - PMA_USER=root
      - PMA_PASSWORD=root
      - MEMORY_LIMIT=256M
      - UPLOAD_LIMIT=256M
      - MAX_EXECUTION_TIME=0
  # selfcert:
  #   container_name: selfcert
  #   build: .devcontainer/selfcert
  #   environment:
  #     DOMAIN: example.local
  #   volumes:
  #     - selfcert:/certs
volumes:
  data:
  selfcert:
    # NOTE: docker volume create selfcert
    name: selfcert
    external: true
